// Auto-generated by MSBuild. Do not edit manually.
// Generated at: 2026-04-17 23:55:52

namespace YuWanCard.Utils;

public static class BaseLibVersion
{
    public const string Version = "3.0.6";
}
